import React, { useState, useEffect, useMemo, useRef } from 'react';
import { motion, AnimatePresence } from 'motion/react';
import { Wand2, Copy, Check, Download, RotateCcw } from 'lucide-react';
import { HighlightedLine } from './ChapterSection';

interface ConfigWizardProps {
  open: boolean;
  onClose: () => void;
}

interface WizardChoices {
  leader: string;
  numbers: string;
  colorscheme: string;
  plugins: string[];
}

const STEPS = [
  {
    key: 'leader' as const,
    prompt: 'Pick your <leader> key',
    hint: 'The prefix for your personal keymaps. Space is the modern favorite — huge target, both thumbs.',
    options: [
      { value: 'space', label: '<Space>', detail: 'the modern default' },
      { value: ',', label: ',', detail: 'classic, close to home row' },
      { value: '\\', label: '\\', detail: "Vim's original default" }
    ]
  },
  {
    key: 'numbers' as const,
    prompt: 'How should line numbers behave?',
    hint: 'Hybrid shows the real number on your line and relative offsets everywhere else — perfect for 5j / 12k jumps.',
    options: [
      { value: 'hybrid', label: 'Hybrid', detail: 'absolute on cursor, relative elsewhere' },
      { value: 'absolute', label: 'Absolute', detail: 'plain 1, 2, 3…' },
      { value: 'relative', label: 'Relative', detail: 'pure offsets for motion golf' }
    ]
  },
  {
    key: 'colorscheme' as const,
    prompt: 'Choose a colorscheme',
    hint: 'All four are actively maintained and treesitter-aware. You can :colorscheme away later.',
    options: [
      { value: 'tokyonight', label: 'tokyonight', detail: 'neon city night' },
      { value: 'catppuccin', label: 'catppuccin', detail: 'soothing pastel' },
      { value: 'gruvbox', label: 'gruvbox', detail: 'retro warm contrast' },
      { value: 'rose-pine', label: 'rose-pine', detail: 'muted elegance' }
    ]
  },
  {
    key: 'plugins' as const,
    prompt: 'Pick your starter plugins',
    hint: 'Toggle with the number keys, confirm with Enter. lazy.nvim bootstraps automatically.',
    multi: true,
    options: [
      { value: 'telescope', label: 'telescope.nvim', detail: 'fuzzy find everything' },
      { value: 'treesitter', label: 'nvim-treesitter', detail: 'real syntax awareness' },
      { value: 'lualine', label: 'lualine.nvim', detail: 'a proper statusline' },
      { value: 'gitsigns', label: 'gitsigns.nvim', detail: 'git hunks in the gutter' },
      { value: 'which-key', label: 'which-key.nvim', detail: 'discover your own keymaps' },
      { value: 'oil', label: 'oil.nvim', detail: 'edit dirs like buffers' }
    ]
  }
];

const PLUGIN_SPECS: Record<string, string[]> = {
  telescope: [
    `  { "nvim-telescope/telescope.nvim", dependencies = { "nvim-lua/plenary.nvim" } },`
  ],
  treesitter: [
    `  { "nvim-treesitter/nvim-treesitter", build = ":TSUpdate" },`
  ],
  lualine: [
    `  { "nvim-lualine/lualine.nvim", opts = {} },`
  ],
  gitsigns: [
    `  { "lewis6991/gitsigns.nvim", opts = {} },`
  ],
  'which-key': [
    `  { "folke/which-key.nvim", opts = {} },`
  ],
  oil: [
    `  { "stevearc/oil.nvim", opts = {} },`
  ]
};

const COLORSCHEME_REPOS: Record<string, string> = {
  tokyonight: 'folke/tokyonight.nvim',
  catppuccin: 'catppuccin/nvim',
  gruvbox: 'ellisonleao/gruvbox.nvim',
  'rose-pine': 'rose-pine/neovim'
};

function generateInitLua(c: WizardChoices): string[] {
  const leaderLiteral = c.leader === 'space' ? ' ' : c.leader;
  const lines: string[] = [
    `-- init.lua — generated by nvim://reference config wizard`,
    `-- drop this in ~/.config/nvim/ (or AppData/Local/nvim on Windows)`,
    ``,
    `-- leader must be set before plugins load`,
    `vim.g.mapleader = "${leaderLiteral === '\\' ? '\\\\' : leaderLiteral}"`,
    `vim.g.maplocalleader = "${leaderLiteral === '\\' ? '\\\\' : leaderLiteral}"`,
    ``,
    `-- options`,
    `local opt = vim.opt`
  ];

  if (c.numbers === 'hybrid') {
    lines.push(`opt.number = true`, `opt.relativenumber = true`);
  } else if (c.numbers === 'absolute') {
    lines.push(`opt.number = true`);
  } else {
    lines.push(`opt.relativenumber = true`);
  }

  lines.push(
    `opt.termguicolors = true`,
    `opt.tabstop = 2`,
    `opt.shiftwidth = 2`,
    `opt.expandtab = true`,
    `opt.signcolumn = "yes"`,
    `opt.clipboard = "unnamedplus"`,
    `opt.undofile = true`,
    ``,
    `-- bootstrap lazy.nvim`,
    `local lazypath = vim.fn.stdpath("data") .. "/lazy/lazy.nvim"`,
    `if not vim.uv.fs_stat(lazypath) then`,
    `  vim.fn.system({ "git", "clone", "--filter=blob:none",`,
    `    "https://github.com/folke/lazy.nvim.git", "--branch=stable", lazypath })`,
    `end`,
    `vim.opt.rtp:prepend(lazypath)`,
    ``,
    `-- plugins`,
    `require("lazy").setup({`,
    `  { "${COLORSCHEME_REPOS[c.colorscheme]}", priority = 1000 },`
  );

  c.plugins.forEach((p) => {
    (PLUGIN_SPECS[p] || []).forEach((l) => lines.push(l));
  });

  lines.push(
    `})`,
    ``,
    `vim.cmd.colorscheme("${c.colorscheme === 'catppuccin' ? 'catppuccin' : c.colorscheme}")`,
    ``,
    `-- keymaps`,
    `local map = vim.keymap.set`,
    `map("i", "jk", "<Esc>", { desc = "Exit insert mode" })`,
    `map("n", "<Esc>", "<cmd>nohlsearch<CR>", { desc = "Clear search highlight" })`
  );

  if (c.plugins.includes('telescope')) {
    lines.push(
      `map("n", "<leader>ff", "<cmd>Telescope find_files<CR>", { desc = "Find files" })`,
      `map("n", "<leader>fg", "<cmd>Telescope live_grep<CR>", { desc = "Live grep" })`
    );
  }
  if (c.plugins.includes('oil')) {
    lines.push(`map("n", "-", "<cmd>Oil<CR>", { desc = "Edit parent directory" })`);
  }

  lines.push(``, `-- happy editing. :wq`);
  return lines;
}

export default function ConfigWizard({ open, onClose }: ConfigWizardProps) {
  const [step, setStep] = useState(0);
  const [choices, setChoices] = useState<WizardChoices>({
    leader: 'space',
    numbers: 'hybrid',
    colorscheme: 'tokyonight',
    plugins: ['telescope', 'treesitter']
  });
  const [revealedLines, setRevealedLines] = useState(0);
  const [copied, setCopied] = useState(false);
  const revealTimerRef = useRef<ReturnType<typeof setInterval> | null>(null);

  const isResult = step >= STEPS.length;
  const current = STEPS[Math.min(step, STEPS.length - 1)];
  const generated = useMemo(() => generateInitLua(choices), [choices]);

  useEffect(() => {
    if (open) {
      setStep(0);
      setRevealedLines(0);
      setCopied(false);
    }
  }, [open]);

  // Typed-out reveal of the generated config
  useEffect(() => {
    if (!open || !isResult) return;
    const reduced = window.matchMedia('(prefers-reduced-motion: reduce)').matches;
    if (reduced) {
      setRevealedLines(generated.length);
      return;
    }
    setRevealedLines(0);
    revealTimerRef.current = setInterval(() => {
      setRevealedLines((n) => {
        if (n >= generated.length) {
          if (revealTimerRef.current) clearInterval(revealTimerRef.current);
          return n;
        }
        return n + 1;
      });
    }, 42);
    return () => {
      if (revealTimerRef.current) clearInterval(revealTimerRef.current);
    };
  }, [open, isResult, generated]);

  const selectOption = (value: string) => {
    if (current.multi) {
      setChoices((c) => ({
        ...c,
        plugins: c.plugins.includes(value)
          ? c.plugins.filter((p) => p !== value)
          : [...c.plugins, value]
      }));
    } else {
      setChoices((c) => ({ ...c, [current.key]: value }));
      setStep((s) => s + 1);
    }
  };

  // Keyboard: 1-9 selects, Enter advances, Escape closes
  useEffect(() => {
    if (!open) return;
    const handler = (e: KeyboardEvent) => {
      if (e.key === 'Escape') {
        e.preventDefault();
        e.stopPropagation();
        onClose();
        return;
      }
      if (isResult) return;
      const idx = parseInt(e.key, 10) - 1;
      if (!isNaN(idx) && current.options[idx]) {
        e.preventDefault();
        e.stopPropagation();
        selectOption(current.options[idx].value);
      } else if (e.key === 'Enter') {
        e.preventDefault();
        e.stopPropagation();
        setStep((s) => s + 1);
      }
    };
    window.addEventListener('keydown', handler, true);
    return () => window.removeEventListener('keydown', handler, true);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [open, step, isResult, current, choices]);

  const copyConfig = () => {
    navigator.clipboard.writeText(generated.join('\n'));
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const downloadConfig = () => {
    const blob = new Blob([generated.join('\n')], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'init.lua';
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <AnimatePresence>
      {open && (
        <motion.div key="config-wizard" className="fixed inset-0 z-[60] flex items-center justify-center p-4 vt-overlay-exclude">
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            transition={{ duration: 0.15 }}
            onClick={onClose}
            className="absolute inset-0 bg-zinc-950/70"
          />

          <motion.div
            initial={{ scale: 0.96, y: 14, opacity: 0 }}
            animate={{ scale: 1, y: 0, opacity: 1 }}
            exit={{ scale: 0.96, y: 14, opacity: 0 }}
            transition={{ type: 'spring', stiffness: 460, damping: 32 }}
            className="relative w-full max-w-2xl rounded-2xl border border-zinc-200/60 dark:border-zinc-800/90 bg-white/98 dark:bg-zinc-950/98 shadow-2xl overflow-hidden font-mono select-none"
          >
            {/* Header */}
            <div className="flex items-center justify-between px-4 py-2.5 border-b border-zinc-200/60 dark:border-zinc-800/70 text-[11px] font-bold text-zinc-400 dark:text-zinc-500">
              <span className="flex items-center gap-2">
                <Wand2 className="w-3.5 h-3.5 text-[var(--phosphor)]" />
                <span>nvim://wizard — init.lua generator</span>
              </span>
              <span className="flex items-center gap-2">
                {!isResult && (
                  <span className="text-[10px]">{step + 1} / {STEPS.length}</span>
                )}
                <kbd className="px-1.5 py-0.5 rounded bg-zinc-100 dark:bg-zinc-900 border border-zinc-200 dark:border-zinc-800 text-[10px]">esc</kbd>
              </span>
            </div>

            {!isResult ? (
              <div className="p-6 space-y-5">
                <div>
                  <div className="text-base font-bold text-zinc-900 dark:text-zinc-100 font-sans">{current.prompt}</div>
                  <p className="text-xs text-zinc-500 dark:text-zinc-400 mt-1.5 leading-relaxed font-sans max-w-[52ch]">{current.hint}</p>
                </div>

                <div className="space-y-2">
                  {current.options.map((optn, i) => {
                    const active = current.multi
                      ? choices.plugins.includes(optn.value)
                      : (choices as any)[current.key] === optn.value;
                    return (
                      <button
                        key={optn.value}
                        onClick={() => selectOption(optn.value)}
                        className={`w-full flex items-center gap-3 text-left px-4 py-3 rounded-xl border text-sm transition-colors duration-150 cursor-pointer ${
                          active
                            ? 'border-[var(--phosphor)] bg-emerald-500/[0.06] text-zinc-900 dark:text-zinc-100'
                            : 'border-zinc-200/70 dark:border-zinc-800 text-zinc-600 dark:text-zinc-400 hover:border-zinc-400 dark:hover:border-zinc-600'
                        }`}
                      >
                        <kbd className="px-1.5 py-0.5 rounded bg-zinc-100 dark:bg-zinc-900 border border-zinc-200 dark:border-zinc-800 text-[10px] font-bold shrink-0">{i + 1}</kbd>
                        <span className="font-bold shrink-0">{optn.label}</span>
                        <span className="text-xs opacity-60 truncate">— {optn.detail}</span>
                        {active && <Check className="w-4 h-4 text-[var(--phosphor)] ml-auto shrink-0" />}
                      </button>
                    );
                  })}
                </div>

                <div className="flex items-center justify-between pt-1">
                  <button
                    onClick={() => setStep((s) => Math.max(0, s - 1))}
                    disabled={step === 0}
                    className="text-xs font-bold text-zinc-400 dark:text-zinc-500 hover:text-zinc-600 dark:hover:text-zinc-300 disabled:opacity-30 cursor-pointer transition-colors"
                  >
                    ← back
                  </button>
                  <button
                    onClick={() => setStep((s) => s + 1)}
                    className="px-4 py-2 rounded-lg bg-[var(--text-primary)] text-[var(--bg-void)] text-xs font-bold cursor-pointer active:scale-95 transition-transform"
                  >
                    {step === STEPS.length - 1 ? ':generate ↵' : 'next ↵'}
                  </button>
                </div>
              </div>
            ) : (
              <div>
                {/* Generated buffer */}
                <div className="max-h-[46vh] overflow-y-auto no-scrollbar bg-[#0b0c10] px-5 py-4 text-[11px] md:text-xs leading-relaxed">
                  {generated.slice(0, revealedLines).map((line, i) => (
                    <div key={i} className="flex gap-3 whitespace-pre">
                      <span className="text-zinc-600 w-6 text-right select-none shrink-0">{i + 1}</span>
                      <span>{line ? <HighlightedLine text={line} /> : ' '}</span>
                    </div>
                  ))}
                  {revealedLines < generated.length && <span className="block-caret ml-10" />}
                </div>

                {/* Actions statusline */}
                <div className="flex items-center justify-between px-4 py-3 border-t border-zinc-200/60 dark:border-zinc-800/70">
                  <button
                    onClick={() => { setStep(0); setRevealedLines(0); }}
                    className="flex items-center gap-1.5 text-xs font-bold text-zinc-400 dark:text-zinc-500 hover:text-zinc-600 dark:hover:text-zinc-300 cursor-pointer transition-colors"
                  >
                    <RotateCcw className="w-3.5 h-3.5" />
                    <span>tweak answers</span>
                  </button>
                  <div className="flex items-center gap-2">
                    <button
                      onClick={copyConfig}
                      className="flex items-center gap-1.5 px-3.5 py-2 rounded-lg border border-zinc-200 dark:border-zinc-800 text-xs font-bold text-zinc-700 dark:text-zinc-200 hover:border-[var(--phosphor)] cursor-pointer transition-colors"
                    >
                      {copied ? <Check className="w-3.5 h-3.5 text-[var(--phosphor)]" /> : <Copy className="w-3.5 h-3.5" />}
                      <span>{copied ? 'copied!' : 'copy'}</span>
                    </button>
                    <button
                      onClick={downloadConfig}
                      className="flex items-center gap-1.5 px-3.5 py-2 rounded-lg bg-[var(--text-primary)] text-[var(--bg-void)] text-xs font-bold cursor-pointer active:scale-95 transition-transform"
                    >
                      <Download className="w-3.5 h-3.5" />
                      <span>init.lua</span>
                    </button>
                  </div>
                </div>
              </div>
            )}
          </motion.div>
        </motion.div>
      )}
    </AnimatePresence>
  );
}
